# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='_input_path',
            field=models.FileField(upload_to='upload_image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='_output_path',
            field=models.FileField(upload_to='result_image'),
        ),
    ]
